server:
  port: 9001
  servlet:
    context-path: /admin
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/feiyu-plus?characterEncoding=utf8&useSSL=false&useTimeZone=true&serverTimezone=GMT%2b8&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
      username: root
      password: myroot

# Swagger界面内容配置
swagger:
  title: feiyu-plus 后台API接口文档
  description: feiyu-plus-admin Api Documentation
  version: 1.0.0
  termsOfServiceUrl:
  contact:
    name: xiake
    url:
    email: 1020775653@qq.com

mybatis-plus:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.modules.sys.entity,com.modules.common.entity
  global-config:
    db-column-underline: true
    db-config:
#      # 主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (ID_WORKER,数字类型唯一ID)", 3:"全局唯一ID UUID";
#      id-type: 2
#      # 字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
#      field-strategy: 2
#      # mp2.3+ 全局表前缀 mp_
#      # table-prefix: mp_
#      #驼峰下划线转换
#      db-column-underline: true
#      #刷新mapper 调试神器
#      #refresh-dao: true
#      #数据库大写下划线转换
#      #capital-mode: true
#      # oracle主键策略配置Sequence 序列接口实现类配置
#      # key-generator: com.baomidou.mybatisplus.incrementer.OracleKeyGenerator
#      #逻辑删除配置
#      logic-delete-value: 1                                            # 设置字段值为1，标识已经删除
#      logic-not-delete-value: 0                                        # 默认状态，表示该数据项状态正常
#      sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector   # 自定义 SQL 注入器
      # 自定义 公共字段 自动填充策略接口实现，参考：http://mp.baomidou.com/#/auto-fill
      meta-object-handler: com.config.mybatis.MetaHandler
  configuration:
    map-underscore-to-camel-case: true
#  configuration:
#      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#打印Sql日志
logging:
  level:
    com:
      modules:
        sys:
          mapper: debug