server:
  port: 7001
  servlet:
    context-path: /admin
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/feiyu-plus?characterEncoding=utf8&useSSL=false&useTimeZone=true&serverTimezone=GMT%2b8&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
      username: root
      password: myroot

# Swagger界面内容配置
swagger:
  title: feiyu-plus 后台API接口文档
  description: feiyu-plus-admin Api Documentation
  version: 1.0.0
  termsOfServiceUrl:
  contact:
    name: xiake
    url:
    email: 1020775653@qq.com

mybatis-plus:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.modules.sys.entity,com.modules.common.entity,com.modules.video.entity
  global-config:
    db-column-underline: true
    db-config:
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  configuration:
    map-underscore-to-camel-case: true
#  configuration:
#      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#打印Sql日志
logging:
  level:
    com:
      modules:
        sys:
          mapper: debug